# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=300)),
                ('watts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(default=b'Terraced, Semi, etc', max_length=200)),
                ('number_of_occupants', models.IntegerField(default=1)),
                ('house_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OperationTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_time', models.TimeField()),
                ('off_time', models.TimeField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='des.Appliance')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default=b'Street 1 w/ 30 house etc', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='des.Street'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='des.House'),
        ),
    ]
