# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0002_auto_20160517_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_link',
            name='appliance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='des.Appliance'),
        ),
        migrations.AlterField(
            model_name='table_link',
            name='house_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='des.House'),
        ),
        migrations.AlterField(
            model_name='table_link',
            name='operation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='des.OperationTimes'),
        ),
        migrations.AlterField(
            model_name='table_link',
            name='street_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='des.Street'),
        ),
    ]
