# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0004_remove_operationtimes_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtimes',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operationtimes',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
