# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0006_appliance_default_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='house_list',
            field=models.CharField(default='0', max_length=1000),
            preserve_default=False,
        ),
    ]
