# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0007_street_house_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.CharField(max_length=99999)),
                ('house_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='des.House')),
            ],
        ),
    ]
